collision = false;
showDesc = false;
name = "Sample Modification"
sizetimer = 50;
shrink = true;
spriteHeight = sprite_height*2;
box_size = 80;
thisInstance = instance_create_layer(x,y,"Entities",Modification);
pickUpTimeout = 30;
resizeAllowed = true;