draw_self();
draw_set_color(c_black);
draw_text(0,room_height/10,"Mouse and Keyboard : ");
draw_text(0,room_height/10+25,"Use WASD to move, the mouse to aim and left click to shoot.");
draw_text(0,room_height/10+50,"You can equip weapons by pressing E when your Player is on top of them.");
draw_text(0,room_height/10+75,"You can show the Description of a Weapon by hovering over it when its lying on the floor.");
draw_text(0,room_height/10+100,"You can put a Modification in your left slot with Q and in your right slot with E");
draw_text(0,room_height/10+125,"You can show all stats of your equipped stuff with TAB");
draw_text(0,room_height/10+200,"ESC to exit game, or open menus/get back to the game when youre in-game");
draw_text(0,room_height/10+275,"Controller :");
draw_text(0,room_height/10+300,"Left Stick to Move, Right stick to Aim and Shoot");
draw_text(0,room_height/10+325,"A to equip weapon");
draw_text(0,room_height/10+350,"X to put Modification in left slot, B to put it in right slot");
draw_text(0,room_height/10+375,"Y to show descriptions when things are lying on floor and Player is hovering on them");
draw_text(0,room_height/10+400,"LB or RB to show inventory descriptions");
draw_text(0,room_height/10+425,"Start to exit game, or open menus/get back to the game when youre in-game");
draw_text(0,room_height/10+600,"Unfortunately you can only click Buttons, Click to Exit");